"""add_tables

Revision ID: 1d1780a89a42
Revises: 7f56eca4479c
Create Date: 2024-08-03 13:24:11.130574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d1780a89a42'
down_revision: Union[str, None] = '7f56eca4479c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('patronymic', sa.String(length=32), nullable=False),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('employer',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_user'),
    sa.UniqueConstraint('id')
    )
    op.create_table('resume',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('speciality', postgresql.ENUM('разработка', 'аналитика', 'devops', 'системное администрирование', 'дата-инженерия', 'машинное обучение', 'управление проектами', 'руководство разработкой', 'архитектура проектов', 'информационная безопасность', 'тестирование', name='speciality'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('job_place',
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('speciality', postgresql.ENUM('разработка', 'аналитика', 'devops', 'системное администрирование', 'дата-инженерия', 'машинное обучение', 'управление проектами', 'руководство разработкой', 'архитектура проектов', 'информационная безопасность', 'тестирование', name='speciality'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('resume_tool',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('user', 'patronymic')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('vacancy', sa.Column('is_publish', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'is_publish')
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('patronymic', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_table('resume_tool')
    op.drop_table('job_place')
    op.drop_table('resume')
    op.drop_table('employer')
    op.drop_table('employee')
    # ### end Alembic commands ###
