"""3_vacancy_link

Revision ID: 6e7cf2c7a5c4
Revises: f64fc2a89309
Create Date: 2024-06-08 18:08:21.779906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7cf2c7a5c4'
down_revision: Union[str, None] = 'f64fc2a89309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'link')
    # ### end Alembic commands ###
