"""2_vacancy_uq_tool

Revision ID: f64fc2a89309
Revises: 7654737218ed
Create Date: 2024-06-02 13:18:40.960262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64fc2a89309'
down_revision: Union[str, None] = '7654737218ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'company', ['id'])
    op.create_unique_constraint(None, 'tool', ['name'])
    op.create_unique_constraint(None, 'tool', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'vacancy', ['id'])
    op.create_unique_constraint(None, 'vacancy_tool', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy_tool', type_='unique')
    op.drop_constraint(None, 'vacancy', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tool', type_='unique')
    op.drop_constraint(None, 'tool', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
