"""fix

Revision ID: 76c77cc60d1a
Revises: 60da7f790c90
Create Date: 2024-09-16 09:52:24.945420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76c77cc60d1a"
down_revision: Union[str, None] = "60da7f790c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "answer", ["id"])
    op.create_unique_constraint(None, "city", ["id"])
    op.create_unique_constraint(None, "company", ["id"])
    op.create_unique_constraint(None, "employee", ["id"])
    op.create_unique_constraint(None, "employer", ["id"])
    op.create_unique_constraint(None, "job_place", ["id"])
    op.create_unique_constraint(None, "question", ["id"])
    op.create_unique_constraint(None, "recovery_token", ["id"])
    op.create_unique_constraint(None, "resume", ["id"])
    op.create_unique_constraint(None, "resume_tool", ["id"])
    op.create_unique_constraint(None, "tool", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    op.create_unique_constraint(None, "vacancy", ["id"])
    op.create_unique_constraint(None, "vacancy_tool", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vacancy_tool", type_="unique")
    op.drop_constraint(None, "vacancy", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "tool", type_="unique")
    op.drop_constraint(None, "resume_tool", type_="unique")
    op.drop_constraint(None, "resume", type_="unique")
    op.drop_constraint(None, "recovery_token", type_="unique")
    op.drop_constraint(None, "question", type_="unique")
    op.drop_constraint(None, "job_place", type_="unique")
    op.drop_constraint(None, "employer", type_="unique")
    op.drop_constraint(None, "employee", type_="unique")
    op.drop_constraint(None, "company", type_="unique")
    op.drop_constraint(None, "city", type_="unique")
    op.drop_constraint(None, "answer", type_="unique")
    # ### end Alembic commands ###
