"""add_msg_fk

Revision ID: 87a70e0a78d7
Revises: fb7b557a82cf
Create Date: 2024-09-27 15:55:34.251446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87a70e0a78d7"
down_revision: Union[str, None] = "fb7b557a82cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_evaluation_id"), "evaluation", ["id"])
    op.add_column(
        "message", sa.Column("question_id", sa.UUID(), nullable=True)
    )
    op.add_column("message", sa.Column("answer_id", sa.UUID(), nullable=True))
    op.add_column(
        "message", sa.Column("evaluation_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_message_evaluation_id_evaluation"),
        "message",
        "evaluation",
        ["evaluation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_message_answer_id_answer"),
        "message",
        "answer",
        ["answer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_message_question_id_question"),
        "message",
        "question",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_message_question_id_question"), "message", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_message_answer_id_answer"), "message", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_message_evaluation_id_evaluation"),
        "message",
        type_="foreignkey",
    )
    op.drop_column("message", "evaluation_id")
    op.drop_column("message", "answer_id")
    op.drop_column("message", "question_id")
    op.drop_constraint(op.f("uq_evaluation_id"), "evaluation", type_="unique")
    # ### end Alembic commands ###
